case: "dG_0"
template_dir: "<path to template/structure directory>"
parent_dir: "<path to designs directory>"
output_dir: "<path to output directory>"
stoichiometry: 1

af2_model: "alphafold2_ptm"
path_to_mmseqs: "<path to mmseqs2>"
path_to_colabfold_dbs: "<path to colabfold databases>"

ipsae_params:
  pae_threshold: 15
  distance_threshold: 15
